name: Test Push Stuff on PR

on:
  pull_request

jobs:
  detect_force_push_pr:
    runs-on: ubuntu-latest
    name: Detect Force Push on PR
    if: github.event.action == 'synchronize'
    steps:
      - name: Comment PR
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: 'Hello world ! 👋' });
